apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argo1
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Ashwani028/demo-manifest-files.git
    path: .
    targetRevision: main

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  syncPolicy:
    automated: {}
